### ISSUE TITLE
Extend rucio CLI to support ALTO switch

### ISSUE THREAD

**Issue by giralt** [openalto/ietf-hackathon#13]

**Comment by fno2010** [comment]
@yryang

> requesting update on command line, demonstrating alto as a uniform resource

Probably your requested feature is related to this issue?

Personally, I don't like the originally proposed syntax, `--replica-selection=alto:<URI_to_IRD>:<Resource_ID>`, for two reasons:

1. This looks like a hack for a special case. The syntax will be hard to be generalized to other replica sorting algorithms. Even just for `alto`, if we want to add new arguments in the future, it will also be hard to extend.
2. If you put `<URI_to_IRD>` into the value of this argument, then you cannot use `:` as a separator. Unless you escape the URI. But it makes the command too ugly.

I have two candidate design options:

1. Pass additional arguments using `<key>=<value>` pairs and the `,` separator, which is inspired by mininet cli: `sudo mn --link tc,bw=10,delay=10ms`
2. Pass additional arguments using a JSON, which is inspired by current rucio cli:

    `rucio-admin rse add-protocol --hostname xrd1 --scheme root --prefix //rucio --port 1094 --impl rucio.rse.protocols.xrootd.Default --domain-json '{"wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 1}, "lan": {"read": 1, "write": 1, "delete": 1}}' XRD1`

**Comment by yryang** [comment]
Configuration decision for now:
- Have the alto configuration, which includes the common settings and a list of cost maps,
costmap-bw-available = https://localhost:8081/costmap-bw-available
costmap-routingcost = https://localhost:8081/costmap-bw-routingcost
costmap-latency = https://localhost:8081/costmap-latency
- Make sure we include the alto configuration in the demo slides
- Add into the alto server, the additional .json files and then add the path direct in the flash config

For rucio commandline:
- --replica-selection alto,cm=<costmap-name>,sort=[descend|ascend]  // default is ascend
Demo example:
- rucio download replica-selection alto,cm=costmap-be-available
- rucio download replica-selection alto,cm=costmap-latency

**Comment by fno2010** [comment]
> This switch should not only support ALTO, but also other replica sorting altorithms. I will send a pull request to rucio to address [rucio/rucio#5355](https://github.com/rucio/rucio/issues/5355) first.

The PR rucio/rucio#5364 has been merged. This issue can be closed.
