### ISSUE TITLE
Documenting comprehensive and complete story

### ISSUE THREAD

**Issue by MattSlm** [openalto/ietf-hackathon#33]
Quoting Jordi: 
"Thanks @MattSlm. Is this the umbrella ticket we discussed to write a user friendly document explaining the complete story? If so, at a high level the idea here will be:

The story starts from the very beginning (LHC experiment collides atoms generating gigantic datasets, see for instance https://cds.cern.ch/record/2276551)
The datasets are kept in storage.
The Rucio server replicates the datasets to various nodes
Scientists download datasets by choosing from the various available replicas.
Scientists can use ALTO to optimize the download decision
At each step, please specify the protocols that are being used (e.g., xrootd, Rucio, ALTO).

Suggest that URLS to the various protocol documents be included (xrootd, Rucio, RFCs, etc.) so a reader can dig more into them if he/she wants to learn about the details.

Please also use our hackathon example network to illustrate at each step how things get done (file upload, download, etc.):

````
              Rucio
      1Mbps    |     5Mbps
      25ms     |     25ms
  s1 --------- s3 ----------- s4 -- XRD3
  |            |              |
  |            | 25ms         | 50ms
  |            | 1Mbps        | 2Mbps
  |            |              |
 XRD1          s2 -- XRD2     s5 -- XRD4
````
Can I suggest that in the above diagram we separate the Rucio server from the Rucio client (where the scientist is located)? I think it will make it more realistic and functionally easier to understand. (Note: I have created a ticket to modify the network configuration to accommodate for this change: #31)

The document should be written so that both a non-technical person can understand the story flow and a also for a technical person to understand how the various protocols are used end-to end. So good artistic writing skills are needed there :)

The story should also be written in a compelling manner, motivating the use case and the benefits of using ALTO. Thks."

**Comment by fno2010** [comment]
Closed by PR #44
