### ISSUE TITLE
Write the 113 ALTO Hackathon Story

### ISSUE THREAD

**Issue by giralt** [openalto/ietf-hackathon#8]

**Comment by yryang** [comment]
Step 0.  We make sure that the topology is setup properly (there is a bottleneck link, and majority of RSEs use the bottleneck and only one RSE is a high through path)
   Assume 10 RSEs, the prob. 1/10 to pick the right one, we can pick it.

Step 1. Scientist logins to a container running rucio.

Step 2. Scientist downloads a file using rucio
    rucio download --pfn=<filename> // default, which is random
    after entering the command, 
       at the terminal, displays the key steps of the working progress
          - display it finds a list of candidates
          - picks on randomly
       system pops a window showing the downloading rate 
          // use a simple redis database and writes the sequence, and display it
       after a few min, the scientist can stop it, the figure stays on the screen//tab. in a browser
        
Step 3.  Repeat step 2, using 
    rucio download --pfn=<filename> --replica-selection=alto:<serverIP>:bw-available
    Display the rate

// alternative, we run step 2 w/o display, and step 3 w/o display
// Step 4: single plot: run step 2, a couple times, and then step 3 a single
//    the random from step 2 and the alto one from step 3
    plot of both at normalized starting time
